As suggested by 'vogelwk': Exit when the PRE command fails

diff --git a/makebackup b/makebackup
--- a/makebackup
+++ b/makebackup
@@ -23,10 +23,10 @@
 #------------------------------------------------------------------------------#
 #                    V e r s i o n   i n f o r m a t i o n                     #
 #------------------------------------------------------------------------------#
-# $Id:: makebackup 44 2013-08-06 17:43:42 tonk                              $: #
-# $Revision:: 44                                                            $: #
+# $Id:: makebackup 45 2013-08-06 17:52:16 tonk                              $: #
+# $Revision:: 45                                                            $: #
 # $Author:: Ton Kersten <github@tonkersten.com>                             $: #
-# $Date:: 2013-08-06 17:43:42 +0200 (Tue, 06 Aug 2013)                      $: #
+# $Date:: 2013-08-06 17:52:16 +0200 (Tue, 06 Aug 2013)                      $: #
 # $Hash::                                                                   $: #
 #------------------------------------------------------------------------------#
 #             E n d   o f   v e r s i o n   i n f o r m a t i o n              #
@@ -239,6 +239,13 @@ then
 	echo
 	syslog "Prebackup command ended with returncode ${THISRC}"
 	rm -f /tmp/${IAM}_${$}
+
+	if [[ ${THISRC} != 0 ]]
+	then
+		echo "Exit because of failed 'pre' command"
+		syslog "Exit because of failed 'pre' command"
+		exit ${THISRC}
+	fi
 fi
 
 #------------------------------------------------------------------------------#
